version: '3.1'
services:
  wordpress:
    container_name: 'wp'
    build: .
    restart: unless-stopped
    links:
      - mysql
    volumes:
      - ./src/themes/:/var/www/html/wp-content/themes
      - ./src/plugins/:/var/www/html/wp-content/plugins
      - ./src/uploads/:/var/www/html/wp-content/uploads
      - ./build:/build
      - "node-modules:/var/node_modules"
    ports:
      - 80:80
      - 3000:3000
      - 3001:3001
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - SITE_URL=${SITE_URL}
    command: /bin/bash -c "apache2-foreground & gulp"
  mysql:
    container_name: "wp-db"
    image: mysql
    restart: unless-stopped
    volumes:
       - ./build/sql:/build/sql
       - ./src/initial-db:/docker-entrypoint-initdb.d
    env_file:
      - .env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    - mysql:db
    restart: always
    ports:
     - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
volumes:
  node-modules:
